services:

  postgres:
    image: postgres:15.3-alpine
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 2s
      retries: 5

  memcached:
    container_name: memcached
    image: memcached:1.6-alpine
    restart: always
    ports:
      - '11212:11212'
    healthcheck:
      test: [ "CMD", "nc","-z","127.0.0.1","11211"]
      interval: 5s
      timeout: 2s
      retries: 5

  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/
    entrypoint:
      - ./entrypoint.sh
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_healthy
    ports:
      - '8000:8000'
    env_file:
      - .env
    container_name: backend

volumes:
  postgres:
